<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.widdo</groupId>
        <artifactId>widdo-nexus</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>nexus-examples</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>nexus-examples</name>
    <description>nexus-examples</description>
    <packaging>jar</packaging>

    <properties>
        <java.version>21</java.version>
    </properties>

    <dependencies>
        <!--1. 引入starter-->
        <dependency>
            <groupId>com.widdo</groupId>
            <artifactId>nexus-spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>

        <!--2. 按需引入数据库适配器-->
        <dependency>
            <groupId>com.widdo</groupId>
            <artifactId>nexus-neo4j</artifactId>
        </dependency>

        <dependency>
            <groupId>com.widdo</groupId>
            <artifactId>nexus-hadoop</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>build-info</goal> <!-- 生成 build-info.properties -->
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
